# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_consumtion_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbDebugLog = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDebugLog.setGeometry(QtCore.QRect(520, 620, 1051, 271))
        self.gbDebugLog.setObjectName("gbDebugLog")
        self.teAlgLog = QtWidgets.QTextEdit(self.gbDebugLog)
        self.teAlgLog.setGeometry(QtCore.QRect(30, 50, 1001, 241))
        self.teAlgLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.teAlgLog.setObjectName("teAlgLog")
        self.gbDebugPlt = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDebugPlt.setGeometry(QtCore.QRect(530, 20, 641, 471))
        self.gbDebugPlt.setObjectName("gbDebugPlt")
        self.gbAlgClass = QtWidgets.QGroupBox(self.centralwidget)
        self.gbAlgClass.setGeometry(QtCore.QRect(30, 20, 451, 521))
        self.gbAlgClass.setObjectName("gbAlgClass")
        self.twAlgRules = QtWidgets.QTreeWidget(self.gbAlgClass)
        self.twAlgRules.setGeometry(QtCore.QRect(20, 30, 411, 471))
        self.twAlgRules.setObjectName("twAlgRules")
        self.twAlgRules.headerItem().setText(0, "1")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(530, 510, 641, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Code Time Consumption Visualizer"))
        self.gbDebugLog.setTitle(_translate("MainWindow", "Debug Log"))
        self.gbDebugPlt.setTitle(_translate("MainWindow", "Consumption Show"))
        self.gbAlgClass.setTitle(_translate("MainWindow", "Code Structure Tree"))
