# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_consumption_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 614)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 614))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 614))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbDebugPlt = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDebugPlt.setGeometry(QtCore.QRect(650, 10, 591, 491))
        self.gbDebugPlt.setObjectName("gbDebugPlt")
        self.gbAlgClass = QtWidgets.QGroupBox(self.centralwidget)
        self.gbAlgClass.setGeometry(QtCore.QRect(30, 20, 291, 241))
        self.gbAlgClass.setObjectName("gbAlgClass")
        self.twAlgRules = QtWidgets.QTreeWidget(self.gbAlgClass)
        self.twAlgRules.setGeometry(QtCore.QRect(10, 20, 271, 211))
        self.twAlgRules.setObjectName("twAlgRules")
        self.twAlgRules.headerItem().setText(0, "1")
        self.hsCurFrame = QtWidgets.QSlider(self.centralwidget)
        self.hsCurFrame.setGeometry(QtCore.QRect(650, 520, 591, 22))
        self.hsCurFrame.setOrientation(QtCore.Qt.Horizontal)
        self.hsCurFrame.setObjectName("hsCurFrame")
        self.gbDebugPie = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDebugPie.setGeometry(QtCore.QRect(70, 270, 501, 281))
        self.gbDebugPie.setObjectName("gbDebugPie")
        self.gbDebugLog = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDebugLog.setGeometry(QtCore.QRect(330, 20, 291, 241))
        self.gbDebugLog.setObjectName("gbDebugLog")
        self.teAlgLog = QtWidgets.QTextEdit(self.gbDebugLog)
        self.teAlgLog.setGeometry(QtCore.QRect(10, 30, 271, 201))
        self.teAlgLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.teAlgLog.setObjectName("teAlgLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Code Time Consumption Visualizer"))
        self.gbDebugPlt.setTitle(_translate("MainWindow", "Consumption Show"))
        self.gbAlgClass.setTitle(_translate("MainWindow", "Code Structure Tree"))
        self.gbDebugPie.setTitle(_translate("MainWindow", "pie"))
        self.gbDebugLog.setTitle(_translate("MainWindow", "Debug Log"))
